FROM python:3.8.10-slim

RUN mkdir -p /home/backend

COPY ./api /home/backend/

RUN cd /home/backend

WORKDIR /home/backend

RUN pip install -r requirements.txt

EXPOSE 8000

ENTRYPOINT ["python3", "manage.py", "runserver", "0.0.0.0:8000"]